### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by phpchess** [reefbarman/gamedb-unity-plugin#1]
It might be obvious to others, but it would be nice which Unity build platforms are supported. PC, IOS, Playstation, Android,.... Also the road-map seems to be missing. It would also be good to know if there is a game level save/load/edit example for the db?

**Comment by reefbarman** [comment]
Hi phpchess,

Thanks for the feedback, it is always helpful!

So yes I should probably clarify the platforms somewhere but it actually is platform agnostic so should work anywhere you want to use it (if it doesn't let me know)

A roadmap should be coming very shortly, I am about to release the Pro version which actually implements a lot of the things I had on the roadmap so it's a bit scarce at the moment

In terms of an example I would eventually love to include some, though a save/load/edit example wouldn't work because editing of the data stored in the GameDB is only available in the editor through the plugin. GameDB's function at runtime is to just provide easy access to things like balancing data or loot tables or enemy lists etc 

If I have misunderstood what you mean about a save/load/edit example let me know

**Comment by phpchess** [comment]
Thanks for the quick response. No, you didn't misunderstand me. To me a database is something I can  read/write/edit/delete information. I am looking for a method of doing this at run-time (I have a level editor and a modular game level, so a db would be ideal). But I respect your use case. But if I understand correctly this will not help me. Thanks again.

**Comment by reefbarman** [comment]
Okay yeah unfortunately this is a read only database at run-time. More a replacement from using json, CSV, XML, hard coding or other formats to store meta-data for a game.

But thanks for the other suggestions I will be updating the documentation with your suggestions
