### ISSUE TITLE
No CRUD?

### ISSUE THREAD

**Issue by sonicviz** [reefbarman/gamedb-unity-plugin#2]
Hi,
I bought this on the expectation you could actually write to the database, as I need to populate it with a large amount of in-game initial data. But it seems to be read only with get.

How can you call it a DB with only one way functionality?

Can I get a refund?

**Comment by reefbarman** [comment]
Hi sonicviz,

I am sorry to hear that the GameDB doesn't quite provide the functionality that you expect. 

Can I ask what your requirements are? While runtime editing of the database is not supported, it does come with various methods of adding data that can be either done by hand or script.

The GameDB is intended as a replacement for traditional usages of data stores in CSVs, JSON or other more static storage formats that games tend to use. Avoiding the need to write your own parsing, schema and accessor code.

While the GameDB does technically support CRUD (but its read-only at runtime) the definition of a database doesn't actually require it to support CRUD; "a database is a structured set of data held in a computer, especially one that is accessible in various ways."

If I can't help you solve your use case, a refund can be given. For me to be able to provide further support please contact my support email (listed on the asset store) and please provide your invoice number and date of purchase.

**Comment by sonicviz** [comment]
Hi,
There is no support email on the asset store, just two links to http://www.tristancartledge.com/ (which also has no contact page). Also none on your github here, which is why I was reduced to posting an issue.
If you could contact me via https://sonicviz.com/contact-us/ I can forward you the invoice for refund processing. ty!

re: Definition of db, afaik based on my decades in IT, is it's basically a data store of whatever type you can put data into and get data out of ... flexibly!

I found I had a copy of http://gamedataeditor.com anyway do I can use that.

**Comment by reefbarman** [comment]
Hi,

My email is available via my Publisher page on the Asset Store which can be found by clicking on the Publisher name on the asset page.

Regarding your use-case I would like to understand more, I am actively working on the asset and always looking for ways to improve and provide features people want, plus ensure I am providing adequate support for people having problems with the asset.

You mentioned you need to fill it with initial data, is this something that can only happen at runtime ie. its dynamic data or is it just generated as a once off because there is a lot of it?

I have a feature about to be released that allows adding data via an API via editor scripts for doing things like providing development map-editors or item designers etc where the data is generated automatically! Does this match your use-case?

Thanks

**Comment by sonicviz** [comment]
Thanks, sent you an email.
